In [ ]:
"""
Demo of the histogram (hist) function with a few features.

In addition to the basic histogram, this demo shows a few optional features:

    * Setting the number of data bins
    * The ``normed`` flag, which normalizes bin heights so that the integral of
      the histogram is 1. The resulting histogram is a probability density.
    * Setting the face color of the bars
    * Setting the opacity (alpha value).

"""
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt


# example data
mu = 100  # mean of distribution
sigma = 15  # standard deviation of distribution
x = mu + sigma * np.random.randn(10000)

num_bins = 1000

# the histogram of the data
n, bins, patches = plt.hist(x, num_bins, normed=1, facecolor='green', alpha=0.5)
# add a 'best fit' line
y = mlab.normpdf(bins, mu, sigma)
plt.plot(bins, y, 'r--')
plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title(r'Histogram of IQ: $\mu=100$, $\sigma=15$')

# Tweak spacing to prevent clipping of ylabel
plt.subplots_adjust(left=0.15)
plt.show()

/media/ab/data/utilities/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [9]:
"""
Demo of the histogram (hist) function with a few features.

In addition to the basic histogram, this demo shows a few optional features:

    * Setting the number of data bins
    * The ``normed`` flag, which normalizes bin heights so that the integral of
      the histogram is 1. The resulting histogram is a probability density.
    * Setting the face color of the bars
    * Setting the opacity (alpha value).

"""
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt

mu = [58, 89, 109, 152, 309]  # mean of distribution
sigma = [68.395382, 17.030365, 70.130632, 24.006091, 24.539265]  # standard deviation of distribution

# example data
for i in range(len(mu)):
    x = mu[i] + sigma[i] * np.random.randn(30000)
    num_bins = 50
    # the histogram of the data
    #n, bins, patches = plt.hist(x, num_bins, normed=1, facecolor='green', alpha=0.5)
    # add a 'best fit' line
    y = mlab.normpdf(bins, mu[i], sigma[i])
    plt.plot(bins, y, 'r--')
    plt.xlabel('Position')
    plt.ylabel('Probability')
    plt.title(r'Histogram of IQ: $\mu=100$, $\sigma=15$')

    # Tweak spacing to prevent clipping of ylabel
    plt.subplots_adjust(left=0.15)
    plt.show()

In [29]:
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt

# example data
#mu = 100  # mean of distribution
#sigma = 15  # standard deviation of distribution
x = sigma
#x = [68.395382, 17.030365, 70.130632, 24.006091, 24.539265]
#x = mu + sigma * np.random.randn(50)
#print "x: ", x
num_bins = len(x) / 100
# the histogram of the data
n, bins, patches = plt.hist(x, num_bins, normed=1, facecolor='blue', alpha=0.5)
# add a 'best fit' line
#y = mlab.normpdf(bins, mu, sigma)
#plt.plot(bins, y, 'r--')
plt.xlabel('Sigma')
plt.ylabel('Probability')
plt.title(r'Histogram of IQ: $\mu=100$, $\sigma=15$')

# Tweak spacing to prevent clipping of ylabel
#plt.subplots_adjust(left=0.15)
plt.show()

In [33]:
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt

#sigma = [4,6,7,3,5,7,5,3,7,9,6,37,3,5,3]
# example data
#mu = 100  # mean of distribution
#sigma = 15  # standard deviation of distribution
x = sigma
#print x
#x = [68.395382, 17.030365, 70.130632, 24.006091, 24.539265]
#x = mu + sigma * np.random.randn(50)
#print "x: ", x
num_bins = len(x) / 2
print "num_bins: ", num_bins
# the histogram of the data
n, bins, patches = plt.hist(x, num_bins, normed=1, facecolor='blue', alpha=0.5)
# add a 'best fit' line
#y = mlab.normpdf(bins, mu, sigma)
#plt.plot(bins, y, 'r--')
plt.xlabel('Sigma')
plt.ylabel('Probability')
plt.title(r'Histogram of IQ: $\mu=100$, $\sigma=15$')

# Tweak spacing to prevent clipping of ylabel
#plt.subplots_adjust(left=0.15)
plt.show()

num_bins:  7


In [4]:
import matplotlib.pyplot as plt
import numpy as np
data = np.random.rand(4,4)
print data

column_labels = list('ABCD')
row_labels = list('WXYZ')
data = np.random.rand(4,4)
fig, ax = plt.subplots()
heatmap = ax.pcolor(data, cmap=plt.cm.Blues)

# put the major ticks at the middle of each cell
ax.set_xticks(np.arange(data.shape[0])+0.5, minor=False)
ax.set_yticks(np.arange(data.shape[1])+0.5, minor=False)

# want a more natural, table-like display
ax.invert_yaxis()
ax.xaxis.tick_top()

ax.set_xticklabels(row_labels, minor=False)
ax.set_yticklabels(column_labels, minor=False)
plt.show()


[[ 0.81378121  0.79246896  0.9273605   0.99463367]
 [ 0.04815658  0.07339348  0.74790871  0.76722213]
 [ 0.62680269  0.0614431   0.77471341  0.27450294]
 [ 0.85442103  0.68241525  0.05049004  0.05652584]]


In [3]:
import matplotlib.pyplot as plt


AttributeError: 'module' object has no attribute 'cbook'